services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    user: "${UID}:${GID}"
    ports:
      - "8082:80" # Using port 8082 to avoid conflict with Pi-hole
    volumes:
      - ./data:/data
      - ./config:/config
      - /path/to/your/files:/srv # Change this to the directory you want to browse file
    restart: unless-stopped